author: Vector Institute
copyright: Vector Institute
execute:
  execute_notebooks: false
html:
  google_analytics_id: __G_ANALYTICS_ID__
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  notebook_interface: jupyterlab
logo: https://vectorinstitute.ai/wp-content/uploads/2022/11/logo-vector-institute-full-colour-01.png
repository:
  branch: booklet
  path_to_book: ./
  url: https://github.com/SajjadPSavoji/forecasting-bootcamp
title: SajjadPSavoji/forecasting-bootcamp
